name: h2
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25406
title: One Theosis Three Narrators
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e9d792'
    - '#b78b4a'
    - '#52391a'
    - '#905314'
  brandStrength: 0.375
  lightness: 0.7085106
  saturation: 0.7404255
  rhythmicContrast: 0.75
purpose: []
